- pipeline.id: devops-dev-error
  path.config: "/usr/share/logstash/pipeline/outsystems/error.conf"
- pipeline.id: devops-dev-extension
  path.config: "/usr/share/logstash/pipeline/outsystems/extension.conf"
- pipeline.id: devops-dev-integration
  path.config: "/usr/share/logstash/pipeline/outsystems/integration.conf"
- pipeline.id: devops-dev-mobile-request
  path.config: "/usr/share/logstash/pipeline/outsystems/mobile-request.conf"
- pipeline.id: devops-dev-timer
  path.config: "/usr/share/logstash/pipeline/outsystems/timer.conf"
- pipeline.id: devops-dev-web-reference
  path.config: "/usr/share/logstash/pipeline/outsystems/web-reference.conf"
- pipeline.id: devops-dev-web-request
  path.config: "/usr/share/logstash/pipeline/outsystems/web-request.conf"
- pipeline.id: devops-dev-web-service
  path.config: "/usr/share/logstash/pipeline/outsystems/web-service.conf"
- pipeline.id: devops-general
  path.config: "/usr/share/logstash/pipeline/outsystems/general.conf"
- pipeline.id: devops-request-events
  path.config: "/usr/share/logstash/pipeline/outsystems/request-event.conf"
